[package]
name = "projectm-rs"
version = "1.0.4"
edition = "2021"
rust-version = "1.65"
authors = ["AnomieVision <anomievision@gmail.com.com>"]
description = "Bindings for ProjectM"
license = "	LGPL-3.0-or-later"
repository = "https://github.com/projectM-visualizer/projectm-rs" #https://github.com/anomievision/projectm-rs
keywords = ["visualization", "audio", "sound",  "projectm"]
categories = ["multimedia", "multimedia::video", "multimedia::audio"]
readme = "README.md"

[dependencies]
libc = "0.2.139"
projectm-sys = { version = "1.0.5", features = ["playlist"] }
rand = "0.8.5"

# *needed for test_sdl*
# sdl2 = "0.35.2"

[[example]]
name = "sdl"

[features]
default = ["playlist"]
playlist = []
example = ["sdl2"]

[dependencies.sdl2]
version = "0.35.2"
optional = true


